name: 'Branch'
on: [push]
jobs:
  dependency-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Use NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'
          cache: 'yarn'

      - name: Install Packages
        run: yarn install

      - name: Build Packages
        run: yarn build

      - name: Prettier
        run: yarn prettier:check

