name: 'Branch'
on: [push]
jobs:
  dependency-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '20.0.0'   
      - name: Cache node modules
        uses: actions/cache@v2
        id: node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Packages
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build Packages
        run: yarn build

      - name: Prettier
        run: yarn prettier:check

